import { useEffect, useState } from "react";
import { ArrowRight, Info, MousePointer2, ShieldCheck, Sparkles, X } from "lucide-react";
import { DROP_LABELS, money, OCCUPATIONS, percent, reportFor, TOOLS, TRAITS } from "../../data/studyEngine";
import Summary from "../ui/Summary";

function Bars({ rows, total, onPick }) {
  return rows.length ? <div className="analytics-bars">{rows.map(([name, count]) => <button key={name} onClick={() => onPick?.(name)} disabled={!onPick}><span>{name}</span><i><em style={{ width: `${percent(count, total)}%` }} /></i><b>{count}명</b></button>)}</div> : <p className="empty-copy">표시할 결과가 없습니다.</p>;
}
const tally = items => Object.entries(items.reduce((acc, item) => ({ ...acc, [item]: (acc[item] || 0) + 1 }), {})).sort((a, b) => b[1] - a[1]);

export default function IntegratedReport({ study, openRun }) {
  const [evidenceId, setEvidenceId] = useState(null);
  const [showValidationMethod, setShowValidationMethod] = useState(false);
  useEffect(() => {
    if (!evidenceId) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const close = event => { if (event.key === "Escape") setEvidenceId(null); };
    window.addEventListener("keydown", close);
    return () => { document.body.style.overflow = previousOverflow; window.removeEventListener("keydown", close); };
  }, [evidenceId]);
  const report = reportFor(study);
  const person = study.personas.find(p => p.persona_id === evidenceId);
  const finding = report.results.find(r => r.persona_id === evidenceId);
  if (!study.run) return <div className="flow-card report-empty"><Sparkles size={26} /><h3>아직 실행 결과가 없습니다.</h3><p>Persona를 만든 뒤 Ask와 Act를 관찰하면 여기서 같은 결과를 분석할 수 있습니다.</p><button className="primary" onClick={() => openRun()}>AI 테스트 시작 <ArrowRight size={15} /></button></div>;
  const reached = study.screens.map(s => [`${s.id} ${s.label}`, report.acts.filter(r => r.act.path.includes(s.id)).length]);
  const intentions = [5, 4, 3, 2, 1].map(n => [`${n}점`, report.asks.filter(r => r.ask.usage_intention === n).length]);
  const needed = tally(report.asks.flatMap(r => r.ask.needed_features));
  const unneeded = tally(report.asks.flatMap(r => r.ask.unneeded_features));
  const concerns = report.concerns.map(([code, count]) => [DROP_LABELS[code] || code, count]);
  const dropReasons = report.dropReasons.map(([code, count]) => [DROP_LABELS[code] || code, count]);
  const averageTurns = report.turns.length ? (report.turns.reduce((n, x) => n + x, 0) / report.turns.length).toFixed(1) : "—";
  const related = (predicate) => report.results.find(predicate)?.persona_id;
  return <div className="integrated-report">
    <div className="report-intro"><div><small>AI PERSONA ANALYSIS · DEMO</small><h2>{study.product.name} 검증 결과</h2><p>과제 “{study.task}” · 같은 AI Persona {report.both.length}명의 Ask와 Act를 비교합니다.</p></div><button className="secondary" onClick={() => openRun()}>실행 기록 보기 <ArrowRight size={15} /></button></div>
    <section className="saydo-card"><div><small>핵심 발견 · 말과 행동의 차이</small><h3>쓰겠다는 답과 과제를 완료한 행동을 함께 봅니다.</h3><p>이 수치는 실제 구매 전환율이나 예측 정확도가 아닙니다.</p></div><div className="saydo-values"><span><small>Ask 긍정 · 4~5점</small><b>{report.positiveRate}%</b><em>{report.positive}/{report.both.length}명</em></span><span><small>Act 목표 도달</small><b>{report.completionRate}%</b><em>{report.complete}/{report.both.length}명</em></span><span><small>Say–Do Gap · 완료 − 긍정</small><b>{report.gap > 0 ? "+" : ""}{report.gap}%p</b><em>동일 Persona 유효 쌍 기준</em></span></div></section>
    <div className="summaries integrated-summaries"><Summary label="Ask 평균 사용 의향" value={`${report.averageIntent}/5`} sub={`긍정 ${report.positive}명`} icon={Sparkles} /><Summary label="Act 과제 완료율" value={`${report.completionRate}%`} sub={`완료 ${report.complete}명 · 이탈 ${report.drops.length}명`} icon={MousePointer2} /><Summary label="주요 이탈 화면" value={report.dropScreens[0] ? (study.screens.find(s => s.id === report.dropScreens[0][0])?.label || report.dropScreens[0][0]) : "없음"} sub={report.dropScreens[0] ? `${report.dropScreens[0][1]}명 이탈` : "이탈 없음"} icon={Info} /><Summary label="결과 해석" value="AI 시뮬레이션" sub="실사용자 결과로 확정할 수 없음" icon={ShieldCheck} /></div>
    <section className="flow-card reliability-card" aria-labelledby="reliability-heading"><div className="flow-card-head"><div><span className="section-kicker">RELIABILITY · 결과 해석</span><h3 id="reliability-heading">이 결과를 어떻게 읽어야 하나요?</h3><p>이 리포트는 체험용 AI Persona의 응답과 행동을 집계합니다. 실제 사용자 행동이나 예측 정확도로 해석할 근거는 아직 없습니다.</p></div><span className="reliability-badge">실측 검증 자료 없음</span></div><div className="reliability-grid"><div><b>주요 이탈 화면</b><span>AI 패널에서 관찰된 위치</span><small>실사용자 이탈 순위와의 재현 여부는 미검증</small></div><div><b>과제 완료율</b><span>이 테스트의 AI 시뮬레이션 값</span><small>실사용자 대비 낙관·보수 편향은 미검증</small></div><div><b>이탈 이유</b><span>Persona가 표현한 이유</span><small>실사용자 발화와의 일치 여부는 미검증</small></div></div><button className="text-button reliability-toggle" onClick={() => setShowValidationMethod(v => !v)} aria-expanded={showValidationMethod}>검증 방법 자세히 보기 <ArrowRight size={14} /></button>{showValidationMethod && <div className="reliability-method"><p>향후 별도 Real Validation 자료가 준비되면, 동일 과제에서 실제 사용자와 AI 패널의 <b>이탈 화면 순위</b>, <b>완료율 차이의 방향</b>, <b>주요 이탈 이유</b>를 비교해 결과 해석에 반영할 수 있습니다.</p><p>현재는 해당 비교 자료가 없으므로 신뢰도 점수나 오차 범위를 표시하지 않습니다. 의사결정 전에는 실제 사용자 조사로 확인하세요.</p></div>}</section>
    <section className="flow-card"><div className="flow-card-head"><div><h3>Persona별 결과와 근거</h3><p>한 사람의 의견, 이동 경로, 결과를 한 행에서 연결합니다. 선택하면 원래 행동까지 볼 수 있습니다.</p></div></div><div className="persona-report-table"><div className="persona-report-head"><span>Persona</span><span>Ask · 제품 평가</span><span>Act · 사용 행동</span><span>결과</span></div>{report.results.map(r => { const p = study.personas.find(x => x.persona_id === r.persona_id); const mismatch = r.ask?.usage_intention >= 4 && r.act?.end?.result !== "complete"; return <button key={r.persona_id} className="persona-report-row" onClick={() => setEvidenceId(r.persona_id)}><span><b>{r.persona_id}</b><small>{p?.age}세 {OCCUPATIONS[p?.occupation]}{mismatch && <em>말≠행동</em>}</small></span><span><b>{r.ask?.usage_intention}/5 · {money(r.ask?.willingness_to_pay)}</b><small>{DROP_LABELS[r.ask?.concern]}</small></span><span><b>{r.act?.path.join(" → ")}</b><small>{r.act?.events.at(-1)?.reason || "기록 없음"}</small></span><span className={r.act?.end?.result === "complete" ? "ok-text" : "drop-text"}>{r.act?.end?.result === "complete" ? "완료" : "이탈"} <ArrowRight size={14} /></span></button>; })}</div></section>
    <div className="report-analysis-grid"><section className="flow-card"><h3>Ask · 기획서 반응</h3><p>{report.asks.length}명이 제품 설명을 읽고 답했습니다.</p><div className="small-stats"><span>긍정 응답 <b>{report.positive}명</b></span><span>지불 의향 중앙값 <b>{money(report.medianWtp)}</b></span><span>유료 지불 의향 <b>{report.paying}명</b></span><span>최대 지불 의향 <b>{money(report.maxWtp)}</b></span><span>최다 우려 <b>{DROP_LABELS[report.concerns[0]?.[0]] || "없음"}</b></span></div><h4>사용 의향 분포</h4><Bars rows={intentions} total={report.asks.length} /><h4>필요한 기능</h4><Bars rows={needed} total={report.asks.length} /><h4>필요하지 않은 기능</h4><Bars rows={unneeded} total={report.asks.length} /><h4>우려 사항</h4><Bars rows={concerns} total={report.asks.length} /></section>
      <section className="flow-card"><h3>Act · 프로토타입 행동</h3><p>{report.acts.length}명의 화면 이동과 중단 결과입니다.</p><div className="small-stats"><span>완료율 <b>{report.completionRate}%</b></span><span>이탈률 <b>{percent(report.drops.length, report.acts.length)}%</b></span><span>평균 행동 <b>{averageTurns}턴</b></span><span>최소 / 최대 <b>{Math.min(...report.turns)} / {Math.max(...report.turns)}턴</b></span><span>최다 이탈 이유 <b>{DROP_LABELS[report.dropReasons[0]?.[0]] || "없음"}</b></span></div><h4>화면별 도달 · Prototype Funnel</h4><Bars rows={reached} total={report.acts.length} onPick={name => setEvidenceId(related(r => r.act.end.result === "drop" && name.startsWith(r.act.end.screen)) || related(r => r.act.path.some(id => name.startsWith(id))))} /><h4>이탈 화면</h4><Bars rows={report.dropScreens.map(([id, count]) => [`${id} ${study.screens.find(s => s.id === id)?.label || ""}`, count])} total={report.acts.length} onPick={name => setEvidenceId(related(r => r.act.end.result === "drop" && name.startsWith(r.act.end.screen)))} /><h4>이탈 이유</h4><Bars rows={dropReasons} total={report.acts.length} onPick={name => setEvidenceId(related(r => r.act.end.result === "drop" && DROP_LABELS[r.act.end.drop_reason] === name))} /></section></div>
    <div className="report-caveat"><Info size={17} /> 모든 수치는 이 테스트의 동일한 AI Persona 실행 결과에서 계산한 데모 값입니다. 실제 사용자 조사와 버전 비교 자료는 아직 제공되지 않습니다.</div>
    {person && finding && <div className="evidence-overlay" onMouseDown={e => e.target === e.currentTarget && setEvidenceId(null)}><aside className="evidence-panel" role="dialog" aria-modal="true" aria-label={`${person.persona_id} 근거 상세`}><header><div><small>분석 근거 · Synthetic User Response</small><h2>{person.persona_id}의 Ask → Act</h2></div><button className="icon-btn" aria-label="근거 닫기" onClick={() => setEvidenceId(null)}><X size={18} /></button></header><div className="evidence-body"><p>{person.age}세 {OCCUPATIONS[person.occupation]} · 기존 도구 {TOOLS[person.existing_tool]}</p><div className="trait-list">{person.traits.map(t => <span key={t}>#{TRAITS[t]}</span>)}</div><h3>Ask · 제품 판단</h3><p>사용 의향 <b>{finding.ask.usage_intention}/5</b> · 지불 의향 <b>{money(finding.ask.willingness_to_pay)}</b></p><p>우려 · {DROP_LABELS[finding.ask.concern]}</p><blockquote>“{finding.ask.reason}”</blockquote><p>필요한 기능 · {finding.ask.needed_features.join(", ") || "없음"}</p><p>필요하지 않은 기능 · {finding.ask.unneeded_features.join(", ") || "없음"}</p><h3>Act · 전체 행동 경로</h3><p>{finding.act.path.map(id => `${id} ${study.screens.find(s => s.id === id)?.label || ""}`).join(" → ")}</p><ol className="agent-timeline">{finding.act.events.map((event, i) => <li key={i}><small>TURN {event.turn} · {event.screen} {study.screens.find(s => s.id === event.screen)?.label}</small><b>{event.action === "click" ? `“${event.target}” 선택 → ${event.to}` : "이탈"}</b><p>“{event.reason}”</p></li>)}</ol><div className={`act-outcome ${finding.act.end.result}`}><b>{finding.act.end.result === "complete" ? "과제 완료" : `${finding.act.end.screen}에서 이탈`}</b><span>{finding.act.end.drop_reason ? DROP_LABELS[finding.act.end.drop_reason] : "목표 화면 도달"}</span></div><button className="primary" onClick={() => { setEvidenceId(null); openRun(person.persona_id); }}>실행 화면에서 전체 Timeline 보기 <ArrowRight size={15} /></button></div></aside></div>}
  </div>;
}
